---
# tasks file for mysql
- name: Sets the root password
  mysql_user: 
   user=root
   password={{ mysql_root_password }}
  become: yes

- name: copy .my.cnf file with wordpress DB password credentials
  template: src=my.cnf.j2 dest=/root/.my.cnf owner=root group=root mode=0600
  become: yes

- name: Create mysql database
  mysql_db: name={{ wp_mysql_db }} state=present
  become: yes

- name: Create mysql user
  mysql_user:
   name={{ wp_mysql_user }}
   password={{ wp_mysql_password }}
   priv=*.*:ALL
  become: yes

